import type { ReviewOutput, ReviewScores } from './schemas/review-output.js';

/** Polish labels for the five English score keys (requirements.md §2 / §4). */
const SCORE_ROWS: ReadonlyArray<{
  key: keyof ReviewScores;
  label: string;
}> = [
  { key: 'correctness', label: 'Poprawność implementacji' },
  { key: 'idiomaticity', label: 'Idiomatyczność' },
  { key: 'complexity', label: 'Złożoność' },
  { key: 'testCoverageVsRisk', label: 'Pokrycie testami względem ryzyka' },
  { key: 'security', label: 'Bezpieczeństwo' },
];

/**
 * Turn finalized review JSON into the PR comment body.
 * Heading must stay `## Code reviewer report` for workflow upsert dedup.
 */
export function formatReviewCommentMarkdown(
  output: ReviewOutput,
  options?: { baseRefLabel?: string },
): string {
  const baseLabel = options?.baseRefLabel ?? 'base...HEAD';
  const scoreLines = SCORE_ROWS.map(
    ({ key, label }) => `| ${label} | ${output.scores[key]} |`,
  ).join('\n');

  const parts: string[] = [
    '## Code reviewer report',
    '',
    `Generated by \`packages/code-reviewer\` against \`${baseLabel}\` (Cursor cloud runtime).`,
    '',
    '## Scores',
    '| Kryterium | Score |',
    '|-----------|------:|',
    scoreLines,
    '',
    `**Werdykt:** ${output.passFail}`,
    '',
    '## Podsumowanie',
    output.summary.trim(),
    '',
    '<details><summary>Structured review JSON</summary>',
    '',
    '```json',
    JSON.stringify(output, null, 2),
    '```',
    '',
    '</details>',
  ];

  return parts.join('\n');
}
